### ISSUE TITLE
Bring Wire to life

### ISSUE THREAD

**Issue by aethaniel** [aethaniel/ExperimentalCore-sam#26]

**Comment by nicolas-rabault** [comment]
Please add I2C management for FLEXCOM and SERCOM (G55). I need it to do somes test on Poppy 2.

**Comment by logos-electromechanical** [comment]
I'm going to start standing this up for the SAM4S this weekend using the CoreRingBuffer library for it.

**Comment by aethaniel** [comment]
Hi @logos-electromechanical, if you don't mind, I would like to cleanup the code first. Won't take lot of time this week end for me.

**Comment by logos-electromechanical** [comment]
No problem -- I can just merge your cleanup once it's ready and then create the pull request once I've had time to test it. I also found this bug report for the Due, along with a fix, and plan to incorporate it: https://forums.adafruit.com/viewtopic.php?f=19&t=73118&p=418612&sid=127b4a11c43f48c5548dc079da4dab84#p418323

**Comment by aethaniel** [comment]
@logos-electromechanical, fyi this task is in progress on my side.

The bug fix from the link above should be in the recent Arduino sam core release (1.6.5). I will check that while testing.

**Comment by aethaniel** [comment]
Will come with https://github.com/aethaniel/ExperimentalCore-sam/tree/wire
