### ISSUE TITLE
Environment VARIANT_NAME

### ISSUE THREAD

**Issue by nicolas-rabault** [aethaniel/ExperimentalCore-sam#36]
I try to compile "blink" for atmel_samg55_xplained_pro. To do that I set VARIANT_NAME on my environement : 

```
$ export VARIANT_NAME=atmel_samg55_xplained_pro
$ echo $VARIANT_NAME
$ atmel_samg55_xplained_pro
```

after that on ExperimentalCore-sam/module/libraries/tests/examples/blink I do 

```
$ make
```

But make keep the default value for VARIANT_NAME...

If I try 

```
$ make VARIENT_NAME=atmel_samg55_xplained_pro
```

Make keep again the default value...

But it seems travis can do it, Travis (job 28.6) do : 

```
$ make --no-builtin-rules VARIANT_NAME=atmel_samg55_xplained_pro -C /home/travis/build/aethaniel/ExperimentalCore-sam/module/libraries/tests/examples/blink
```

And it's working.

**Comment by aethaniel** [comment]
should work with command line:
set VARIANT_NAME=atmel_samg55_xplained_pro ; make all
