### ISSUE TITLE
Help  for SAM4E8E support

### ISSUE THREAD

**Issue by luc-github** [aethaniel/ExperimentalCore-sam#51]
Bonjour :smile: 
I need to get support for SAM4E8E MCU for arduino ide to support a FW for a 3D printer which use this MCU to have an opensource FW

I have started to read docs/ datasheets and realized that I need to redo the variants parts, and the system\CMSIS\Device\ATMEL files.
I am not really familiar with such low level things, but my printer is waiting, so I have to do it.

I just found your repo and looks going to same direction but for other ID, I was wondering if you could give me some direction/advices ? what files need to change and verify ? is datasheet enough to fill all parts ? 
I would be more than happy to push the result to your repo once done

**Comment by luc-github** [comment]
Hmm reading more the code it seems the sam4e8e.h files are already there - thank you ^_^
so just the variants.cpp need to be filled as it does not contain all pins but just serial ones,  I am correct ?

**Comment by aethaniel** [comment]
hello @luc-github, yes, you got it right: you have only to provide your own board description in variants.
You are welcome to bring it here or as a separate module relaying to this one (through dependency).

Be aware I'm more focusing at the moment on obtaining everything working with Makefiles and putting a bit less efforts on Arduino IDE integration, which was working some months ago but may be broken right now (should be easy to fix).

Tell me what you want to do as I'm not against collaborative work ;-)

**Comment by luc-github** [comment]
Great because I was not confortable with boot loader part - yes sure would be happy to share - actually I tested on Due first and did simple sketch to print "yes" on serial, but I did not do a new issue as I was waiting you back from vacations ^_^

Well on my sid,e focus is arduino because easy for end user (and me :wink:) and would be happy to fix it - but need to understand  what is broken actually - I tested 0.1 and not working neither on due

I do due first to understand how your code is working as I only have one board with SAM4E8E and printer is using it so before wiping current FW I want to be sure the new can work
