### ISSUE TITLE
Use git version  with Arduino IDE (1.6.8)

### ISSUE THREAD

**Issue by luc-github** [aethaniel/ExperimentalCore-sam#52]
I know wiki says it is not tested, but integration seems not working, no board is displaying
any tips ?

**Comment by luc-github** [comment]
I replaced my current 1.6.7 due core with the content modules of github and now all the boards are available in boards
If select ATMELSam4E-Xplained pro (programming port) and try to compile an empty sketch

I got a warning :

```
C:\Users\luc.VAIO\AppData\Local\Arduino15\packages\arduino\hardware\sam\1.6.7\cores\arduino\port_sam\CoreWire.cpp:347:4: warning: #warning "todo" [-Wcpp]

   #warning "todo"

    ^
```

and an error :

```
c:/users/luc.vaio/appdata/local/arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld.exe: cannot find -latmel_sam4e_xplained_pro

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Atmel SAM4E-Xplained Pro (Programming Port).
```

Seems atmel_sam4e_xplained_pro library is missing - did I installed in wrong way ?
Sorry if my question is stupid - I am not familliar with this level of configuration

**Comment by luc-github** [comment]
If I replace git version by [ExperimentalCore-sam-0.1.0-win64](https://github.com/aethaniel/ExperimentalCore-sam/releases/download/v0.1.0/ExperimentalCore-sam-0.1.0-win64.tar.bz2) compilation succeed - is it a path issue with git version ?

**Comment by luc-github** [comment]
after investigating : 
libatmel_sam4e_xplained_pro.a is missing in git version
and platform.txt has some typo issues - some path refer to {build.path}/sketch/ and others to {build.path} for the .elf
I did a PR adding /sketch in 2 paths

**Comment by aethaniel** [comment]
thanks for comment, I will check that ASAP

**Comment by luc-github** [comment]
I have cancel my crappy PR - tell me if you need me to redo a clean one

**Comment by aethaniel** [comment]
@luc-github, you seem to be french like me. We can do a skype chat/call if you want. My id is same as here.

**Comment by luc-github** [comment]
yes I am ^_^ 
Great I will add you and setup a call - talk 5 min is more efficient than write 100 pages

**Comment by luc-github** [comment]
close as N/A as current only use makefile - Arduino integration may come later
