### ISSUE TITLE
Reading pin configured as output returns wrong value

### ISSUE THREAD

**Issue by jlbirccyn** [aethaniel/ExperimentalCore-sam#61]
(tested on Arduino DUE)

digitalRead does:

```
  if ( (Ports[g_aPinMap[ulPin].iPort].pGPIO->PIO_PDSR & g_aPinMap[ulPin].ulPin) != 0 )
  {
    return HIGH ;
  }
```
However if the pin is programmed as output, PIO_PDSR seems not to get the pin state. I discover the ATMEL peripherals but maybe PIO_ODSR should be read instead when the pin is programmed as output.

**Comment by aethaniel** [comment]
Thanks for the report @jlbirccyn !
Sorry for late answer, I receive notification mails from github only when I'm cited.
